# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Dotnet Test and Publish Results

on:
  workflow_call:
    inputs:
      project_path:
        description: 'The project path is where the solution file is located'
        required: true

jobs:
  test-and-publish-results:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project_path }}
    
    - name: Build Solution
      run: dotnet build ${{ inputs.project_path }} -c Release
    
    - name: Test
      run: dotnet test ${{ inputs.project_path }} -c Release --verbosity normal --logger "trx;logfilename=testResults.trx"
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/TestResults/*.trx