# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create and Publish Docker Container

on:
  workflow_call:
    inputs:
      PROJECT_PATH:
        description: 'The project path is where the Solution file is located'
        required: true
        type: string
      DOCKERFILE_PATH:
        description: 'Path to the Dockerfile'
        required: true
        type: string
      DOCKER_CONTAINER_NAME:
        description: 'Docker Container Name'
        required: true
        type: string

permissions:
  checks: write
  pull-requests: write

jobs:
  create-and-publish-docker-container:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
        
    - name: Build and Push Docker Images
      if: ${{ success() }}
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.PROJECT_PATH }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.DOCKER_CONTAINER_NAME }}:latest
        file: ${{ inputs.DOCKERFILE }}
